# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpls_lsp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mpls_lsp.proto',
  package='mplspce',
  serialized_pb=_b('\n\x0empls_lsp.proto\x12\x07mplspce\"\xee\x06\n\x03LSP\x12\x0e\n\x06pcc_ip\x18\x01 \x01(\t\x12\'\n\x07lsp_obj\x18\x02 \x01(\x0b\x32\x16.mplspce.LSP.LSPObject\x12\x31\n\x08lspa_obj\x18\x03 \x01(\x0b\x32\x1f.mplspce.LSP.LSPAttributeObject\x12&\n\x03\x65ro\x18\x04 \x03(\x0b\x32\x19.mplspce.LSP.EROSubObject\x12*\n\x05srero\x18\x05 \x03(\x0b\x32\x1b.mplspce.LSP.EROSRSubObject\x12&\n\x03rro\x18\x06 \x03(\x0b\x32\x19.mplspce.LSP.RROSubObject\x12&\n\x03srp\x18\x07 \x01(\x0b\x32\x19.mplspce.LSP.SRPSubObject\x12\x11\n\tbandwidth\x18\x08 \x01(\r\x12\x16\n\x0e\x65ro_list_empty\x18\t \x01(\x08\x1a\xf4\x01\n\tLSPObject\x12\x0f\n\x07plsp_id\x18\x01 \x01(\r\x12\x11\n\tdelegated\x18\x02 \x01(\x08\x12\x0c\n\x04sync\x18\x03 \x01(\x08\x12\x0e\n\x06remove\x18\x04 \x01(\x08\x12\x16\n\x0e\x61\x64ministrative\x18\x05 \x01(\x08\x12\x13\n\x0boperational\x18\x06 \x01(\r\x12\x0e\n\x06\x63reate\x18\x07 \x01(\x08\x12\x15\n\rsymbolic_name\x18\x08 \x01(\t\x12\x15\n\rtunnel_source\x18\t \x01(\t\x12\x17\n\x0ftunnel_endpoint\x18\n \x01(\t\x12\x11\n\ttunnel_id\x18\x0b \x01(\r\x12\x0e\n\x06lsp_id\x18\x0c \x01(\r\x1aU\n\x12LSPAttributeObject\x12\x12\n\nsetup_prio\x18\x01 \x01(\r\x12\x11\n\thold_prio\x18\x02 \x01(\r\x12\x18\n\x10local_protection\x18\x03 \x01(\x08\x1a\x41\n\x0c\x45ROSubObject\x12\r\n\x05loose\x18\x01 \x01(\x08\x12\x0f\n\x07node_ip\x18\x02 \x01(\t\x12\x11\n\tnode_mask\x18\x03 \x01(\r\x1a\x44\n\x0e\x45ROSRSubObject\x12\r\n\x05loose\x18\x01 \x01(\x08\x12\x12\n\nnode_label\x18\x02 \x01(\r\x12\x0f\n\x07node_ip\x18\x03 \x01(\t\x1a\x32\n\x0cRROSubObject\x12\x0f\n\x07node_ip\x18\x01 \x01(\t\x12\x11\n\tnode_mask\x18\x02 \x01(\r\x1a!\n\x0cSRPSubObject\x12\x11\n\x06srp_id\x18\x01 \x01(\r:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LSP_LSPOBJECT = _descriptor.Descriptor(
  name='LSPObject',
  full_name='mplspce.LSP.LSPObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plsp_id', full_name='mplspce.LSP.LSPObject.plsp_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delegated', full_name='mplspce.LSP.LSPObject.delegated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync', full_name='mplspce.LSP.LSPObject.sync', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remove', full_name='mplspce.LSP.LSPObject.remove', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='administrative', full_name='mplspce.LSP.LSPObject.administrative', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operational', full_name='mplspce.LSP.LSPObject.operational', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create', full_name='mplspce.LSP.LSPObject.create', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbolic_name', full_name='mplspce.LSP.LSPObject.symbolic_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tunnel_source', full_name='mplspce.LSP.LSPObject.tunnel_source', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tunnel_endpoint', full_name='mplspce.LSP.LSPObject.tunnel_endpoint', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tunnel_id', full_name='mplspce.LSP.LSPObject.tunnel_id', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lsp_id', full_name='mplspce.LSP.LSPObject.lsp_id', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=595,
)

_LSP_LSPATTRIBUTEOBJECT = _descriptor.Descriptor(
  name='LSPAttributeObject',
  full_name='mplspce.LSP.LSPAttributeObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup_prio', full_name='mplspce.LSP.LSPAttributeObject.setup_prio', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hold_prio', full_name='mplspce.LSP.LSPAttributeObject.hold_prio', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_protection', full_name='mplspce.LSP.LSPAttributeObject.local_protection', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=682,
)

_LSP_EROSUBOBJECT = _descriptor.Descriptor(
  name='EROSubObject',
  full_name='mplspce.LSP.EROSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loose', full_name='mplspce.LSP.EROSubObject.loose', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='mplspce.LSP.EROSubObject.node_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_mask', full_name='mplspce.LSP.EROSubObject.node_mask', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=749,
)

_LSP_EROSRSUBOBJECT = _descriptor.Descriptor(
  name='EROSRSubObject',
  full_name='mplspce.LSP.EROSRSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loose', full_name='mplspce.LSP.EROSRSubObject.loose', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_label', full_name='mplspce.LSP.EROSRSubObject.node_label', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='mplspce.LSP.EROSRSubObject.node_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=819,
)

_LSP_RROSUBOBJECT = _descriptor.Descriptor(
  name='RROSubObject',
  full_name='mplspce.LSP.RROSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='mplspce.LSP.RROSubObject.node_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_mask', full_name='mplspce.LSP.RROSubObject.node_mask', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=821,
  serialized_end=871,
)

_LSP_SRPSUBOBJECT = _descriptor.Descriptor(
  name='SRPSubObject',
  full_name='mplspce.LSP.SRPSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srp_id', full_name='mplspce.LSP.SRPSubObject.srp_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=873,
  serialized_end=906,
)

_LSP = _descriptor.Descriptor(
  name='LSP',
  full_name='mplspce.LSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pcc_ip', full_name='mplspce.LSP.pcc_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lsp_obj', full_name='mplspce.LSP.lsp_obj', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lspa_obj', full_name='mplspce.LSP.lspa_obj', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ero', full_name='mplspce.LSP.ero', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srero', full_name='mplspce.LSP.srero', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rro', full_name='mplspce.LSP.rro', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srp', full_name='mplspce.LSP.srp', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='mplspce.LSP.bandwidth', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ero_list_empty', full_name='mplspce.LSP.ero_list_empty', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LSP_LSPOBJECT, _LSP_LSPATTRIBUTEOBJECT, _LSP_EROSUBOBJECT, _LSP_EROSRSUBOBJECT, _LSP_RROSUBOBJECT, _LSP_SRPSUBOBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=906,
)

_LSP_LSPOBJECT.containing_type = _LSP
_LSP_LSPATTRIBUTEOBJECT.containing_type = _LSP
_LSP_EROSUBOBJECT.containing_type = _LSP
_LSP_EROSRSUBOBJECT.containing_type = _LSP
_LSP_RROSUBOBJECT.containing_type = _LSP
_LSP_SRPSUBOBJECT.containing_type = _LSP
_LSP.fields_by_name['lsp_obj'].message_type = _LSP_LSPOBJECT
_LSP.fields_by_name['lspa_obj'].message_type = _LSP_LSPATTRIBUTEOBJECT
_LSP.fields_by_name['ero'].message_type = _LSP_EROSUBOBJECT
_LSP.fields_by_name['srero'].message_type = _LSP_EROSRSUBOBJECT
_LSP.fields_by_name['rro'].message_type = _LSP_RROSUBOBJECT
_LSP.fields_by_name['srp'].message_type = _LSP_SRPSUBOBJECT
DESCRIPTOR.message_types_by_name['LSP'] = _LSP

LSP = _reflection.GeneratedProtocolMessageType('LSP', (_message.Message,), dict(

  LSPObject = _reflection.GeneratedProtocolMessageType('LSPObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_LSPOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.LSPObject)
    ))
  ,

  LSPAttributeObject = _reflection.GeneratedProtocolMessageType('LSPAttributeObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_LSPATTRIBUTEOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.LSPAttributeObject)
    ))
  ,

  EROSubObject = _reflection.GeneratedProtocolMessageType('EROSubObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_EROSUBOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.EROSubObject)
    ))
  ,

  EROSRSubObject = _reflection.GeneratedProtocolMessageType('EROSRSubObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_EROSRSUBOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.EROSRSubObject)
    ))
  ,

  RROSubObject = _reflection.GeneratedProtocolMessageType('RROSubObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_RROSUBOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.RROSubObject)
    ))
  ,

  SRPSubObject = _reflection.GeneratedProtocolMessageType('SRPSubObject', (_message.Message,), dict(
    DESCRIPTOR = _LSP_SRPSUBOBJECT,
    __module__ = 'mpls_lsp_pb2'
    # @@protoc_insertion_point(class_scope:mplspce.LSP.SRPSubObject)
    ))
  ,
  DESCRIPTOR = _LSP,
  __module__ = 'mpls_lsp_pb2'
  # @@protoc_insertion_point(class_scope:mplspce.LSP)
  ))
_sym_db.RegisterMessage(LSP)
_sym_db.RegisterMessage(LSP.LSPObject)
_sym_db.RegisterMessage(LSP.LSPAttributeObject)
_sym_db.RegisterMessage(LSP.EROSubObject)
_sym_db.RegisterMessage(LSP.EROSRSubObject)
_sym_db.RegisterMessage(LSP.RROSubObject)
_sym_db.RegisterMessage(LSP.SRPSubObject)


# @@protoc_insertion_point(module_scope)
